# Поиск окружности на изображении OpenCV

In [1]:
import cv2
import numpy as np
import imutils
from matplotlib import pyplot as plt


## Нахождение оптимального изображения
### TrackBar

In [ ]:
# name of your image [png, jpg]

name = 'fig1.png'

img = cv2.imread(name)

if __name__ == '__main__':
    def nothing(*arg):
        pass

cv2.namedWindow( "result" ) 
cv2.namedWindow( "settings" ) 

cv2.createTrackbar('h1', 'settings', 0, 255, nothing)
cv2.createTrackbar('s1', 'settings', 0, 255, nothing)
cv2.createTrackbar('v1', 'settings', 0, 255, nothing)
cv2.createTrackbar('h2', 'settings', 255, 255, nothing)
cv2.createTrackbar('s2', 'settings', 255, 255, nothing)
cv2.createTrackbar('v2', 'settings', 255, 255, nothing)
cv2.createTrackbar('bloor', 'settings', 0, 10, nothing)



while True:
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )

    bloor = cv2.getTrackbarPos('bloor', 'settings')
    h1 = cv2.getTrackbarPos('h1', 'settings')
    s1 = cv2.getTrackbarPos('s1', 'settings')
    v1 = cv2.getTrackbarPos('v1', 'settings')
    h2 = cv2.getTrackbarPos('h2', 'settings')
    s2 = cv2.getTrackbarPos('s2', 'settings')
    v2 = cv2.getTrackbarPos('v2', 'settings')

    if bloor % 2 == 0:
        bloor = bloor + 1

    h_min = np.array((h1, s1, v1), np.uint8)
    h_max = np.array((h2, s2, v2), np.uint8)


    hsv = cv2.GaussianBlur(hsv, (bloor, bloor), 2)
    thresh = cv2.inRange(hsv, h_min, h_max)

    cv2.imshow('result', thresh)

    ch = cv2.waitKey(5)
    if ch == 27:
        break

# Нахождение контуров и преобразование изображения

In [1]:
# Load an image
imag = cv2.imread('fig1.jpg')
 
# Resize an image
if imag.shape[1] > 600:
    imag = imutils.resize(imag, width=600, height=400)
clone = imag.copy()

# Convert to grayscale
gray = cv2.cvtColor(clone, cv2.COLOR_BGR2GRAY)
 
# Threshold grayscaled image to get binary image
ret,gray_threshed = cv2.threshold(gray,150,255,cv2.THRESH_BINARY)
 
# Smooth an image
bilateral_filtered_image = cv2.bilateralFilter(gray_threshed, 5, 175, 175)
 
# Find edges
edge_detected_image = cv2.Canny(bilateral_filtered_image, 75, 200)
 
# Find contours
_, contours, _= cv2.findContours(edge_detected_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
 
contour_list = []
for contour in contours:
    approx = cv2.approxPolyDP(contour,0.01*cv2.arcLength(contour,True),True)
    area = cv2.contourArea(contour)
    if ((len(approx) > 8) & (50000 > area > 10000) ):
        contour_list.append(contour)
 
# Draw contours
cv2.drawContours(clone, contour_list, -1, (255,0,0), 2)
 
# Displaying the results
cv2.imshow("Original", imag)
cv2.imshow('Smooth', bilateral_filtered_image)
cv2.imshow('Edge', edge_detected_image)
cv2.imshow('Objects Detected',clone)
cv2.waitKey(0)

NameError: name 'cv2' is not defined

# Hough Circle Transform

## 1 

In [1]:
import cv2
import numpy as np
import imutils
from matplotlib import pyplot as plt

img = cv2.imread('9.png', 0)
img = cv2.medianBlur(img,5)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,10, 
          param1=50,param2=12,minRadius=0,maxRadius=30)

circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # draw the outer circle
    cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # draw the center of the circle
    cv2.circle(cimg,(i[0],i[1]),2,(0,0,255),3)

cv2.imshow('detected circles',cimg)
cv2.waitKey(0)

cv2.destroyAllWindows()

## 2

In [ ]:
import sys
import cv2 as cv
import numpy as np

file =  "9.png"

# Loads an image
src = cv.imread(file, cv.IMREAD_COLOR)
# Check if image is loaded fine
if src is None:
    print ('Error opening image!')
    print ('Usage: hough_circle.py [image_name -- default ' + file + '] \n')
    
    
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
    
gray = cv.medianBlur(gray, 5)

rows = gray.shape[0]
circles = cv.HoughCircles(gray, cv.HOUGH_GRADIENT, 1, rows / 8,
                          param1=100, param2=30,
                          minRadius=1, maxRadius=30)
    
    
if circles is not None:
    circles = np.uint16(np.around(circles))
    print(circles)
    for i in circles[0, :]:
        center = (i[0], i[1])
        print('center=', center, end=' ')
        # circle center
        cv.circle(src, center, 1, (0, 100, 100), 3)
        # circle outline
        radius = i[2]
        print('radius=', radius, end='\n')
        cv.circle(src, center, radius, (255, 0, 255), 3)
    
    
cv.imshow("detected circles", src)
cv.waitKey(0)

[[[ 34  34  29]
  [126 170  29]
  [198  68  29]]]
center= (34, 34) radius= 29
center= (126, 170) radius= 29
center= (198, 68) radius= 29
